### ISSUE TITLE
Linux compile issues

### ISSUE THREAD

**Issue by eliasen** [superpermutators/superperm#41]
The instructions in FastGCM/README.md  have some bugs in Linux.  They probably should read:

`gcc FastDCM.c -O3 -lOpenCL -lm -o FastDCM`

Note that the optimization parameter is a capital O in gcc and you need to link with the math library `-lm`.

Here are the error messages I get when compiling (note that I'm not experienced with compiling OpenCL) but I do get an executable:

```
In file included from /usr/include/CL/cl.h:32,
                 from /usr/include/CL/opencl.h:38,
                 from FastDCM.c:58:
/usr/include/CL/cl_version.h:34:9: note: #pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)
   34 | #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)")
      |         ^~~~~~~
FastDCM.c: In function ‘initOpenCL’:
FastDCM.c:1106:1: warning: ‘clCreateCommandQueue’ is deprecated [-Wdeprecated-declarations]
 1106 | commands = clCreateCommandQueue(context, gpu_device, 0, &clErr);
      | ^~~~~~~~
In file included from /usr/include/CL/opencl.h:38,
                 from FastDCM.c:58:
/usr/include/CL/cl.h:1777:1: note: declared here
 1777 | clCreateCommandQueue(cl_context                     context,
      | ^~~~~~~~~~~~~~~~~~~~
```

**Comment by nagegerg** [comment]
Thanks, I've fixed the compile flags in the README, and added:

#define CL_TARGET_OPENCL_VERSION 120

to the source code, which targets the OpenCL version (1.2) that's required.  I'm not sure if that will make the complaints about clCreateCommandQueue being deprecated go away.

**Comment by eliasen** [comment]
Thanks!  Can confirm that there are no compilation errors now.  Executable still doesn't run with the errors listed in #42 .  Have attempted running with

`./FastDCM gpuName "NVIDIA"`

but same errors.

**Comment by eliasen** [comment]
The fixed page FastGCM/README.md now erroneously (?) shows a command-line to build FastGCMTest instead of FastGCM on Linux.

**Comment by nagegerg** [comment]
Thanks, fixed.
